version: '3.9'
services:
    client:
        container_name: amigo-chat-client
        restart: always
        depends_on:
            - api
        build:
            context: client
            dockerfile: Dockerfile
        ports:
            - '3005:3000'
        environment:
            - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        network_mode: bridge
    api:
        container_name: amigo-chat-api
        restart: always
        build:
            context: server
            dockerfile: Dockerfile
        ports:
            - '3004:4000'
        environment:
            - MONGO_USER=${MONGO_USER}
            - MONGO_PASSWORD=${MONGO_PASSWORD}
            - MONGO_DB=${MONGO_DB}
            - JWT_SECRET=${JWT_SECRET}
        network_mode: bridge
