export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const UPDATE_CONTACTS = 'UPDATE_CONTACTS';
export const UPDATE_PHOTOURL = 'UPDATE_PHOTOURL';
export const UPDATE_PREFERREDSTATUS = 'UPDATE_PREFERREDSTATUS';

export const ONLINE_USERS = 'ONLINE_USERS';
export const CONVERSATIONS = 'CONVERSATIONS';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const CURRENT_CONVERSATION = 'CURRENT_CONVERSATION';
export const CONVERSATION_COUNT = 'CONVERSATION_COUNT';
